openapi: 3.0.0
info:
  title: Places API
  version: '1.0'
  description: The Places API offers real-time access to Foursquare’s global database of rich venue data and user content to power your location-based experiences in your app or website.
  contact:
    name: Fousquare
    url: 'https://developer.foursquare.com/docs'
servers:
  - url: 'https://api.foursquare.com/v2'
    description: Production
paths: {}
components:
  schemas: {}
  securitySchemes:
    clientid:
      name: client_id
      type: apiKey
      in: query
    clientsecret:
      name: client_secret
      type: apiKey
      in: query
