openapi: 3.0.0
info:
  title: Places API
  version: '1.0'
  description: The Places API offers real-time access to Foursquare’s global database of rich venue data and user content to power your location-based experiences in your app or website.
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
