openapi: 3.0.0
info:
  title: Places API
  version: '1.0'
  description: The Places API offers real-time access to Foursquare’s global database of rich venue data and user content to power your location-based experiences in your app or website.
  contact:
    name: Fousquare
    url: 'https://developer.foursquare.com/docs'
servers:
  - url: 'https://api.foursquare.com/v2'
    description: Production
paths:
  /venues/search:
    get:
      summary: Venue Search
      tags: []
      operationId: get-venues-search
      description: 'Returns a list of venues near the current location. '
      parameters:
        - schema:
            type: number
            example: '4074224,-73.99386'
          in: query
          name: ll
          description: |-
            The latitude and longitude coordinates of the user's location. <br/>Format: **latitude(num),longitude(num)**
            <br/>**required** unless `near` is provided
        - schema:
            type: string
            example: Chicago
          in: query
          name: near
          description: |-
            The city near to which the venues are to be returned. 
            <br/>**required** unless `ll` is provided.
        - schema:
            type: integer
            maximum: 100000
            example: 250
          in: query
          name: radius
          description: 'Limits the venues within this radius of specified location. Units are in **meters**.<br/>**Note**: Only valid for requests that use `categoryID` or `query`'
        - schema:
            type: string
            example: pizza
          in: query
          name: query
          description: A keyword for searching venues.
        - schema:
            type: integer
            example: 15
            maximum: 50
          in: query
          name: limit
          description: Number of results to return
        - schema:
            type: string
          in: query
          name: categoryId
          description: 'Categories to limit the results to. To view the list of categories, see <a href="https://developer.foursquare.com/docs/build-with-foursquare/categories/">Venue Categories</a>'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      code:
                        type: integer
                      requestId:
                        type: string
                  response:
                    type: object
                    properties:
                      venues:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            location:
                              type: object
                              properties:
                                address:
                                  type: string
                                crossStreet:
                                  type: string
                                lat:
                                  type: number
                                lng:
                                  type: number
                                labeledLatLngs:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      label:
                                        type: string
                                      lat:
                                        type: number
                                      lng:
                                        type: number
                                distance:
                                  type: integer
                                postalCode:
                                  type: string
                                cc:
                                  type: string
                                city:
                                  type: string
                                state:
                                  type: string
                                country:
                                  type: string
                                formattedAddress:
                                  type: array
                                  items:
                                    type: string
                            categories:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  name:
                                    type: string
                                  pluralName:
                                    type: string
                                  shortName:
                                    type: string
                                  icon:
                                    type: object
                                    properties:
                                      prefix:
                                        type: string
                                      suffix:
                                        type: string
                                  primary:
                                    type: boolean
                            venuePage:
                              type: object
                              properties:
                                id:
                                  type: string
              examples:
                Example:
                  value:
                    meta:
                      code: 0
                      requestId: string
                    response:
                      venues:
                        - id: string
                          name: string
                          location:
                            address: string
                            crossStreet: string
                            lat: 0
                            lng: 0
                            labeledLatLngs:
                              - label: string
                                lat: 0
                                lng: 0
                            distance: 0
                            postalCode: string
                            cc: string
                            city: string
                            state: string
                            country: string
                            formattedAddress:
                              - string
                          categories:
                            - id: string
                              name: string
                              pluralName: string
                              shortName: string
                              icon:
                                prefix: string
                                suffix: string
                              primary: true
                          venuePage:
                            id: string
components:
  schemas: {}
  securitySchemes:
    clientid:
      name: client_id
      type: apiKey
      in: query
    clientsecret:
      name: client_secret
      type: apiKey
      in: query
